-- BANCO DE DADOS
USE MASTER

GO

IF ( NOT EXISTS ( SELECT TABLE_CATALOG AS "Banco" FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG = 'TESTE_PI' ORDER BY TABLE_CATALOG ) )
	CREATE DATABASE TESTE_PI
GO

USE TESTE_PI

GO

IF ( NOT EXISTS ( SELECT NAME FROM SYS.OBJECTS WHERE OBJECT_NAME (OBJECT_ID) = 'PRODUTOS' ) )
	CREATE TABLE PRODUTOS
	(
		ID int IDENTITY PRIMARY KEY
		
		,NOME VARCHAR(30)
	)
GO

-- PRODUTOS  / QUANTIDADE
IF ( NOT EXISTS ( SELECT NAME FROM SYS.COLUMNS WHERE OBJECT_NAME (OBJECT_ID) = 'PRODUTOS' AND NAME = 'QUANTIDADE') )
	ALTER TABLE PRODUTOS ADD QUANTIDADE INTEGER
GO
	UPDATE PRODUTOS SET QUANTIDADE = 0 WHERE QUANTIDADE IS NULL AND DH_INCLUSAO >= DATEADD(MONTH, -6, GETDATE())
GO